// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyz0-kLPOVb6Xcdy-TeAlZGSLE0Gr-TSs',
    appId: '1:910147538423:web:abdc949ec1aa268fd2b2f2',
    messagingSenderId: '910147538423',
    projectId: 'szab-forums-app',
    authDomain: 'szab-forums-app.firebaseapp.com',
    databaseURL: 'https://szab-forums-app-default-rtdb.firebaseio.com',
    storageBucket: 'szab-forums-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzmPaAHLoR9qq_LRQWLn2K__W1njAydvw',
    appId: '1:910147538423:ios:fe74fe3086638c19d2b2f2',
    messagingSenderId: '910147538423',
    projectId: 'szab-forums-app',
    databaseURL: 'https://szab-forums-app-default-rtdb.firebaseio.com',
    storageBucket: 'szab-forums-app.firebasestorage.app',
    iosBundleId: 'com.example.forumsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyz0-kLPOVb6Xcdy-TeAlZGSLE0Gr-TSs',
    appId: '1:910147538423:web:73410e1be2c3136bd2b2f2',
    messagingSenderId: '910147538423',
    projectId: 'szab-forums-app',
    authDomain: 'szab-forums-app.firebaseapp.com',
    databaseURL: 'https://szab-forums-app-default-rtdb.firebaseio.com',
    storageBucket: 'szab-forums-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzmPaAHLoR9qq_LRQWLn2K__W1njAydvw',
    appId: '1:910147538423:ios:fe74fe3086638c19d2b2f2',
    messagingSenderId: '910147538423',
    projectId: 'szab-forums-app',
    databaseURL: 'https://szab-forums-app-default-rtdb.firebaseio.com',
    storageBucket: 'szab-forums-app.firebasestorage.app',
    iosBundleId: 'com.example.forumsApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQlsVTcK0twSaIlNFqJ2k7ehA17deSHo',
    appId: '1:910147538423:android:82c2d437b34c3ed5d2b2f2',
    messagingSenderId: '910147538423',
    projectId: 'szab-forums-app',
    databaseURL: 'https://szab-forums-app-default-rtdb.firebaseio.com',
    storageBucket: 'szab-forums-app.firebasestorage.app',
  );
}
